# Generated by Django 5.2.8 on 2025-11-27 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CHECKUP", "Dental Check-up / Consultation"),
                            ("CLEANING", "Oral Prophylaxis / Cleaning"),
                            ("FLUORIDE", "Fluoride Treatment"),
                            ("SEALANTS", "Sealants"),
                            ("FILLING", "Tooth Filling / Restoration"),
                            ("CROWN", "Crown and Bridge"),
                            ("VENEERS", "Veneers"),
                            ("ROOTCANAL", "Root Canal Treatment"),
                            ("EXTRACTION", "Tooth Extraction"),
                            ("SURGICAL_EXTRACTION", "Surgical Extraction"),
                            ("WISDOM_TOOTH", "Wisdom Tooth Removal"),
                            ("BRACES_METAL", "Braces - Metal"),
                            ("BRACES_CERAMIC", "Braces - Ceramic"),
                            ("CLEAR_ALIGNERS", "Clear Aligners / Invisalign"),
                            ("DENTURES_PARTIAL", "Partial Dentures"),
                            ("DENTURES_FULL", "Full Dentures"),
                            ("IMPLANT", "Dental Implants"),
                            ("SCALING_ROOTPLANING", "Scaling and Root Planing"),
                            ("GUM_SURGERY", "Gum Surgery"),
                            ("TEETH_WHITENING", "Teeth Whitening"),
                            ("SMILE_MAKEOVER", "Smile Makeover"),
                            ("DENTAL_XRAY", "Dental X-ray"),
                            ("PANORAMIC_XRAY", "Panoramic X-ray"),
                            ("PEDIATRIC_CHECKUP", "Child Check-up"),
                            ("PEDIATRIC_FLUORIDE", "Fluoride for Kids"),
                            ("PULPOTOMY", "Pulpotomy / Pediatric Filling"),
                        ],
                        default="CHECKUP",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="clinic.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name_at_time", models.CharField(max_length=150)),
                ("price_at_time", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="clinic.invoice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinic.service"
                    ),
                ),
            ],
        ),
    ]
