# Generated by Django 5.2.8 on 2025-11-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("CHECKUP", "Dental Check-up / Consultation"),
                    ("CLEANING", "Oral Prophylaxis / Cleaning"),
                    ("FLUORIDE", "Fluoride Treatment"),
                    ("SEALANTS", "Sealants"),
                    ("FILLING", "Tooth Filling / Restoration"),
                    ("CROWN", "Crown and Bridge"),
                    ("VENEERS", "Veneers"),
                    ("ROOTCANAL", "Root Canal Treatment"),
                    ("EXTRACTION", "Tooth Extraction"),
                    ("SURGICAL_EXTRACTION", "Surgical Extraction"),
                    ("WISDOM_TOOTH", "Wisdom Tooth Removal"),
                    ("BRACES_METAL", "Braces - Metal"),
                    ("BRACES_CERAMIC", "Braces - Ceramic"),
                    ("CLEAR_ALIGNERS", "Clear Aligners / Invisalign"),
                    ("DENTURES_PARTIAL", "Partial Dentures"),
                    ("DENTURES_FULL", "Full Dentures"),
                    ("IMPLANT", "Dental Implants"),
                    ("SCALING_ROOTPLANING", "Scaling and Root Planing"),
                    ("GUM_SURGERY", "Gum Surgery"),
                    ("TEETH_WHITENING", "Teeth Whitening"),
                    ("SMILE_MAKEOVER", "Smile Makeover"),
                    ("DENTAL_XRAY", "Dental X-ray"),
                    ("PANORAMIC_XRAY", "Panoramic X-ray"),
                    ("PEDIATRIC_CHECKUP", "Child Check-up"),
                    ("PEDIATRIC_FLUORIDE", "Fluoride for Kids"),
                    ("PULPOTOMY", "Pulpotomy / Pediatric Filling"),
                    ("MEDICAL_CERTIFICATE", "Medical Certificate"),
                ],
                default="CHECKUP",
                max_length=50,
            ),
        ),
    ]
