# Generated by Django 5.2.8 on 2025-12-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_invoice_created_by_invoice_is_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
