# Generated by Django 5.2.8 on 2025-12-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_patient_is_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="is_archived",
        ),
    ]
