# Generated by Django 5.2.8 on 2025-12-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_remove_patient_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
