"""
Django settings for dental_clinic project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
try:
    import dj_database_url
except Exception:
    dj_database_url = None
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')
# Read DEBUG from env so production can disable it
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# Render domain and localhost
# Default includes common Render domain patterns and local IP for mobile testing
default_hosts = "127.0.0.1,localhost,.onrender.com"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", default_hosts).split(",")
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS]

# Allow a developer machine IP for physical device testing when DEBUG is enabled.
# You can override the IP using the DEV_HOST_IP env var.
DEV_HOST_IP = os.getenv('DEV_HOST_IP', '192.168.100.14')
if DEBUG and DEV_HOST_IP and DEV_HOST_IP not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(DEV_HOST_IP)


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'clinic',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "dental_clinic.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "clinic/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                'django.template.context_processors.debug',
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dental_clinic.wsgi.application"

LOGIN_REDIRECT_URL = '/clinic/services/'
LOGOUT_REDIRECT_URL = '/'

# Database configuration
# Prefer a single DATABASE_URL env var (Render managed Postgres).
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    # If dj_database_url isn't available, we handle sqlite urls locally and otherwise raise
    if dj_database_url is None:
        if DATABASE_URL.startswith('sqlite'):
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }
        else:
            raise ImproperlyConfigured(
                'DATABASE_URL is set but the Python package "dj-database-url" is not installed in this environment.\n'
                'Install it with: pip install dj-database-url'
            )
    else:
        # Only require SSL in production (when DEBUG is False)
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=not DEBUG)
        }
elif os.getenv('DB_HOST'):
    # legacy individual DB_* env vars (kept for compatibility)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'dentalprojectdb'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # Fallback to local SQLite for convenience during development on Windows/macOS
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
# Use leading slash so `static` template tag generates absolute paths (e.g. /static/...) for templates
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS / REST Framework for Snack Expo frontend
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'
if not CORS_ALLOW_ALL_ORIGINS:
    # Allow Snack Expo, localhost, and Render domain
    cors_origins = os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'https://snack.expo.dev,http://localhost:3000,http://localhost:8000,http://127.0.0.1:3000,http://127.0.0.1:8000'
    ).split(',')
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins]
CORS_ALLOW_CREDENTIALS = True

# Security Settings for Production
if not DEBUG:
    # Temporarily disable SSL redirect for debugging Render issues
    # SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Allow Render-hosted domains and any host in ALLOWED_HOSTS (except IPs/localhost)
    env_csrf = os.getenv('CSRF_TRUSTED_ORIGINS')
    if env_csrf:
        CSRF_TRUSTED_ORIGINS = [u.strip() for u in env_csrf.split(',') if u.strip()]
    else:
        csrf_origins = ['https://*.render.com']
        for host in ALLOWED_HOSTS:
            if not host:
                continue
            # skip bare IPs and localhost for https origins
            if host in ('127.0.0.1', 'localhost') or host.replace('.', '').isdigit():
                continue
            # strip leading dot for wildcard subdomains
            host_name = host.lstrip('.')
            csrf_origins.append(f'https://{host_name}')
        CSRF_TRUSTED_ORIGINS = csrf_origins
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_SECURITY_POLICY = {
        'default-src': ("'self'",),
    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}
